---
Name: registration_module
After: 'framework/*','cms/*', 'openstack/*'
---
Member:
  extensions:
    - OpenStackMember
SecurityAdmin:
  extensions:
    - SecurityAdminDecorator
SiteConfig:
  extensions:
    - CustomSiteConfigRegistration